name: Add issues to project board

on:
  issues:
    types: [opened, reopened, transferred]
  pull_request:
    types: [opened, reopened]

jobs:
  add-to-project:
    name: Add to Quack! project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v2
        with:
          # User-owned project: https://github.com/users/<username>/projects/<number>
          # Org-owned project:  https://github.com/orgs/<org>/projects/<number>
          project-url: https://github.com/users/Andre-asn/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
